[build]
  # Directory to change to before starting a build
  base = "."
  
  # Build command
  command = "npm run build"
  
  # Directory to deploy (Vite builds to 'dist' by default)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PWA Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Static asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
